<?php

namespace App\Http\Controllers\HT50;

use App\Http\Controllers\Base\ResouceController;
use App\Models\HT50\Gift;
use App\Models\HT50\GiftCustomer;
use App\Models\HT50\T4;
use App\Models\HT50\InforCustomerSurvey;
use App\Models\HT50\Revenue;
use App\Services\HT50\InforCustomerSurveyService;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AccumulateController extends ResouceController
{
    function __construct(InforCustomerSurveyService $service)
    {
        parent::__construct($service, array('active' => 'survey', 'group' => 'manager'), '.accumulate');
    }

    public function index()
    {
        $data = Revenue::groupBy('level')->select('level', DB::raw('count(*) as total'))->get();
        $levels = ["Total" => 0, "Gold" => 0, "HT" => 0, "Platinum" => 0, "Silver" => 0, "Titan" => 0];
        $total = 0;
        foreach ($data as $level) {
            $total = $total + $level['total'];
            $levels[$level['level']] = $level['total'];
        }
        $levels["Total"] = $total;
        return parent::index()->with($levels); // TODO: Change the autogenerated stub
    }

    public function store(Request $request)
    {
        $customer = Revenue::where('code', $request->customer_code)->first();
        if (empty($customer)) return view('errors.404');
        $gift = Gift::find($request->gift);
        $customer->used = $customer->used+$gift->coin;
        $customer->save();
        $data['customer_code']=$request->customer_code;
        $data['gift_id']=$request->gift;
        $data['code']=$request->code;
        $data['created_by']='47';
        return GiftCustomer::create($data);
    }

    public function show($id)
    {
        if ($id == '') return view('errors.404');
        $customer = T4::where('code', $id)->first();
        if ($customer) {
            $voucher = InforCustomerSurvey::where('code', $id)->first();
            if ($voucher) return view('survey.notOver', ['voucher' => $customer->voucher]);
            return view('survey.index', ['code' => $customer->code]);
        }
        return view('errors.404');
    }

    public function edit($id)
    {
        $data = Revenue::groupBy('level')->select('level', DB::raw('count(*) as total'))->where('role_pt', $id)->get();
        $levels = ["Total" => 0, "Gold" => 0, "Member" => 0, "Platinum" => 0, "Silver" => 0, "Titan" => 0];
        $total = 0;
        foreach ($data as $level) {
            $total = $total + $level['total'];
            $levels[$level['level']] = $level['total'];
        }
        $levels["Total"] = $total;
        return view('survey.accumulate-edit')->with($levels)->with(['role' => $id]);
    }
}
