<?php

namespace App\Http\Controllers\HT30;

use App\Http\Controllers\Base\ResouceController;
use App\Http\Controllers\Controller;
use App\Models\HT30\Key;
use App\Models\HT30\Result;
use App\Services\HT30\ResultService;
use Illuminate\Http\Request;

class ResultController extends ResouceController
{
    function __construct(ResultService $service)
    {
        $this->middleware('auth');
        parent::__construct($service, array('active' => 'okrs'), '.key');
    }

    public function store(Request $request)
    {
        $key=Key::find($request->key_id);
        $result= $key->result-($key->minus*$request->number);
        $key->update(array('result'=>$result));
        return parent::storeRequest($request);
    }
    public function destroy($id)
    {
        $result=Result::find($id);
        $key=Key::find($result->key_id);
        $res= $key->result+($key->minus*$result->number);
        $key->update(array('result'=>$res));
        return $result->update(array('status'=>1)); // TODO: Change the autogenerated stub
    }
}
